# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
